// <auto-generated />
using System;
using BlazorSQLiteV2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorSQLiteV2.data.migrations
{
    [DbContext(typeof(BlazorSQLiteDbContext))]
    [Migration("20221215023001_1st Migration")]
    partial class _1stMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("BlazorSQLiteV2.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PostDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PostPictureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.HasIndex("PostPictureId")
                        .IsUnique();

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("BlazorSQLiteV2.Data.PostPicture", b =>
                {
                    b.Property<int>("PostPictureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostPictureName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostPictureUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PostPictureId");

                    b.ToTable("PostPictures");
                });

            modelBuilder.Entity("BlazorSQLiteV2.Data.Post", b =>
                {
                    b.HasOne("BlazorSQLiteV2.Data.PostPicture", "PostPicture")
                        .WithOne("PostId")
                        .HasForeignKey("BlazorSQLiteV2.Data.Post", "PostPictureId");

                    b.Navigation("PostPicture");
                });

            modelBuilder.Entity("BlazorSQLiteV2.Data.PostPicture", b =>
                {
                    b.Navigation("PostId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
